version: '3'
services:

  postgres:
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-volume: